substitutions:
  _TF_VERSION: 1.3.5
steps:
  - id: 'docker tag'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - '${_BACKEND_IMAGE}:${COMMIT_SHA}'
      - '${_BACKEND_IMAGE}:${COMMIT_SHA}'
      - '${_BACKEND_IMAGE}:${TAG_NAME}'
