substitutions:
  _TF_VERSION: 1.3.5
steps:
  - id: 'tf build'
    name: 'hashicorp/terraform:${_TF_VERSION}'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd deploy/google-cloud/terraform/build
        terraform init "-backend-config=bucket=${_TFSTATE_BUCKET}"
        terraform apply --auto-approve
  - id: 'tf deploy'
    name: 'hashicorp/terraform:${_TF_VERSION}'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY}" == true ]; then
          cd deploy/google-cloud/terraform/deploy
          terraform init "-backend-config=bucket=${_TFSTATE_BUCKET}"
          terraform apply --auto-approve
        fi
