substitutions:
  _TF_VERSION: 1.3.5
steps:
  - id: 'tf deploy'
    name: 'hashicorp/terraform:${_TF_VERSION}'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd deploy/google-cloud/terraform/deploy
        terraform init "-backend-config=bucket=${_TFSTATE_BUCKET}"
        terraform apply \
          -var="project_id=${PROJECT_ID}" \
          -var="region=${_REGION}" \
          -var="backend_image=${_BACKEND_IMAGE}" \
          -var="domain=${_DOMAIN}" \
          --auto-approve
