substitutions:
  _TF_VERSION: 1.3.5
  _BACKEND_IMAGE_FULL: '${_BACKEND_IMAGE}:${COMMIT_SHA}'
steps:
  - id: 'docker build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag'
      - '${_BACKEND_IMAGE_FULL}'
      - '.'
  - id: 'docker push'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_BACKEND_IMAGE_FULL}'
  - id: 'tf apis and cloudbuild sa roles'
    name: 'hashicorp/terraform:${_TF_VERSION}'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd deployment/google-cloud/terraform/apis_and_cloudbuild_sa_roles
        terraform init "-backend-config=bucket=${_TFSTATE_BUCKET}"
        terraform apply \
          -var="project_id=${PROJECT_ID}" \
          --auto-approve
  - id: 'tf deployment'
    name: 'hashicorp/terraform:${_TF_VERSION}'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd deployment/google-cloud/terraform/deployment
        terraform init "-backend-config=bucket=${_TFSTATE_BUCKET}"
        terraform apply \
          -var="project_id=${PROJECT_ID}" \
          -var="region=${_REGION}" \
          -var="backend_image=${_BACKEND_IMAGE_FULL}" \
          -var="domain=${_DOMAIN}" \
          --auto-approve
